s="Mansi Patel"

print(s)
print(s.capitalize())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.swapcase())
print(s.center(40,"*"))
print(s.count("a"))
print(s.endswith("el"))
print(s.startswith("ma"))
print(s.find("patel"))
print(s.index("a",1))
print("mansi963".isalnum())
print("mansi".isalnum())
print("963".isalnum())
print("Mansi".isalpha())
print("963".isnumeric()) 
print(s.istitle())
print(s.isupper())
print(s.islower())
print("hello". replace("l","w"))
